In [30]:
from ucimlrepo import fetch_ucirepo 
  
# fetch dataset 
chronic_kidney_disease = fetch_ucirepo(id=336) 
  
# data (as pandas dataframes) 
X = chronic_kidney_disease.data.features # 24 independent features 
y = chronic_kidney_disease.data.targets # Target column 
  
  
# metadata 
print(chronic_kidney_disease.metadata) 
  
# variable information 
print(chronic_kidney_disease.variables)

{'uci_id': 336, 'name': 'Chronic Kidney Disease', 'repository_url': 'https://archive.ics.uci.edu/dataset/336/chronic+kidney+disease', 'data_url': 'https://archive.ics.uci.edu/static/public/336/data.csv', 'abstract': 'This dataset can be used to predict the chronic kidney disease and it can be collected from the hospital nearly 2 months of period.', 'area': 'Other', 'tasks': ['Classification'], 'characteristics': ['Multivariate'], 'num_instances': 400, 'num_features': 24, 'feature_types': ['Real'], 'demographics': ['Age'], 'target_col': ['class'], 'index_col': None, 'has_missing_values': 'yes', 'missing_values_symbol': 'NaN', 'year_of_dataset_creation': 2015, 'last_updated': 'Mon Mar 04 2024', 'dataset_doi': '10.24432/C5G020', 'creators': ['L. Rubini', 'P. Soundarapandian', 'P. Eswaran'], 'intro_paper': None, 'additional_info': {'summary': 'We use the following representation to collect the dataset\r\n                        age\t\t-\tage\t\r\n\t\t\tbp\t\t-\tblood pressure\r\n\t\t\tsg\t\t-\tspecific gravity\r\n\t\t\tal\t\t-   \talbumin\r\n\t\t\tsu\t\t-\tsugar\r\n\t\t\trbc\t\t-\tred blood cells\r\n\t\t\tpc\t\t-\tpus cell\r\n\t\t\tpcc\t\t-\tpus cell clumps\r\n\t\t\tba\t\t-\tbacteria\r\n\t\t\tbgr\t\t-\tblood glucose random\r\n\t\t\tbu\t\t-\tblood urea\r\n\t\t\tsc\t\t-\tserum creatinine\r\n\t\t\tsod\t\t-\tsodium\r\n\t\t\tpot\t\t-\tpotassium\r\n\t\t\themo\t\t-\themoglobin\r\n\t\t\tpcv\t\t-\tpacked cell volume\r\n\t\t\twc\t\t-\twhite blood cell count\r\n\t\t\trc\t\t-\tred blood cell count\r\n\t\t\thtn\t\t-\thypertension\r\n\t\t\tdm\t\t-\tdiabetes mellitus\r\n\t\t\tcad\t\t-\tcoronary artery disease\r\n\t\t\tappet\t\t-\tappetite\r\n\t\t\tpe\t\t-\tpedal edema\r\n\t\t\tane\t\t-\tanemia\r\n\t\t\tclass\t\t-\tclass\t', 'purpose': None, 'funded_by': None, 'instances_represent': None, 'recommended_data_splits': None, 'sensitive_data': None, 'preprocessing_description': None, 'variable_info': 'We use 24 + class = 25 ( 11  numeric ,14  nominal)\r\n1.Age(numerical)\r\n  \t  \tage in years\r\n \t2.Blood Pressure(numerical)\r\n\t       \tbp in mm/Hg\r\n \t3.Specific Gravity(nominal)\r\n\t  \tsg - (1.005,1.010,1.015,1.020,1.025)\r\n \t4.Albumin(nominal)\r\n\t\tal - (0,1,2,3,4,5)\r\n \t5.Sugar(nominal)\r\n\t\tsu - (0,1,2,3,4,5)\r\n \t6.Red Blood Cells(nominal)\r\n\t\trbc - (normal,abnormal)\r\n \t7.Pus Cell (nominal)\r\n\t\tpc - (normal,abnormal)\r\n \t8.Pus Cell clumps(nominal)\r\n\t\tpcc - (present,notpresent)\r\n \t9.Bacteria(nominal)\r\n\t\tba  - (present,notpresent)\r\n \t10.Blood Glucose Random(numerical)\t\t\r\n\t\tbgr in mgs/dl\r\n \t11.Blood Urea(numerical)\t\r\n\t\tbu in mgs/dl\r\n \t12.Serum Creatinine(numerical)\t\r\n\t\tsc in mgs/dl\r\n \t13.Sodium(numerical)\r\n\t\tsod in mEq/L\r\n \t14.Potassium(numerical)\t\r\n\t\tpot in mEq/L\r\n \t15.Hemoglobin(numerical)\r\n\t\themo in gms\r\n \t16.Packed  Cell Volume(numerical)\r\n \t17.White Blood Cell Count(numerical)\r\n\t\twc in cells/cumm\r\n \t18.Red Blood Cell Count(numerical)\t\r\n\t\trc in millions/cmm\r\n \t19.Hypertension(nominal)\t\r\n\t\thtn - (yes,no)\r\n \t20.Diabetes Mellitus(nominal)\t\r\n\t\tdm - (yes,no)\r\n \t21.Coronary Artery Disease(nominal)\r\n\t\tcad - (yes,no)\r\n \t22.Appetite(nominal)\t\r\n\t\tappet - (good,poor)\r\n \t23.Pedal Edema(nominal)\r\n\t\tpe - (yes,no)\t\r\n \t24.Anemia(nominal)\r\n\t\tane - (yes,no)\r\n \t25.Class (nominal)\t\t\r\n\t\tclass - (ckd,notckd)', 'citation': None}}
     name     role         type demographic              description  \
0     age  Feature      Integer         Age                     None
1      bp  Feature      Integer        None           blood pressure
2      sg  Feature  Categorical        None         specific gravity
3      al  Feature  Categorical        None                  albumin
4      su  Feature  Categorical        None                    sugar
5     rbc  Feature       Binary        None          red blood cells
6      pc  Feature       Binary        None                 pus cell
7     pcc  Feature       Binary        None          pus cell clumps
8      ba  Feature       Binary        None                 bacteria
9     bgr  Feature      Integer        None     blood glucose random
10     bu  Feature      Integer        None               blood urea
11     sc  Feature   Continuous        None         serum creatinine
12    sod  Feature      Integer        None                   sodium
13    pot  Feature   Continuous        None                potassium
14   hemo  Feature   Continuous        None               hemoglobin
15    pcv  Feature      Integer        None       packed cell volume
16   wbcc  Feature      Integer        None   white blood cell count
17   rbcc  Feature   Continuous        None     red blood cell count
18    htn  Feature       Binary        None             hypertension
19     dm  Feature       Binary        None        diabetes mellitus
20    cad  Feature       Binary        None  coronary artery disease
21  appet  Feature       Binary        None                 appetite
22     pe  Feature       Binary        None              pedal edema
23    ane  Feature       Binary        None                   anemia
24  class   Target       Binary        None           ckd or not ckd

           units missing_values
0           year            yes
1          mm/Hg            yes
2           None            yes
3           None            yes
4           None            yes
5           None            yes
6           None            yes
7           None            yes
8           None            yes
9         mgs/dl            yes
10        mgs/dl            yes
11        mgs/dl            yes
12         mEq/L            yes
13         mEq/L            yes
14           gms            yes
15          None            yes
16     cells/cmm            yes
17  millions/cmm            yes
18          None            yes
19          None            yes
20          None            yes
21          None            yes
22          None            yes
23          None            yes
24          None             no

On  target column: <br> - ckd means Chronic Kidney Disease <br>
                     - not ckd: means not Chronic Kidney Disease

In [31]:
chronic_kidney_disease.metadata.additional_info.summary

'We use the following representation to collect the dataset\r\n                        age\t\t-\tage\t\r\n\t\t\tbp\t\t-\tblood pressure\r\n\t\t\tsg\t\t-\tspecific gravity\r\n\t\t\tal\t\t-   \talbumin\r\n\t\t\tsu\t\t-\tsugar\r\n\t\t\trbc\t\t-\tred blood cells\r\n\t\t\tpc\t\t-\tpus cell\r\n\t\t\tpcc\t\t-\tpus cell clumps\r\n\t\t\tba\t\t-\tbacteria\r\n\t\t\tbgr\t\t-\tblood glucose random\r\n\t\t\tbu\t\t-\tblood urea\r\n\t\t\tsc\t\t-\tserum creatinine\r\n\t\t\tsod\t\t-\tsodium\r\n\t\t\tpot\t\t-\tpotassium\r\n\t\t\themo\t\t-\themoglobin\r\n\t\t\tpcv\t\t-\tpacked cell volume\r\n\t\t\twc\t\t-\twhite blood cell count\r\n\t\t\trc\t\t-\tred blood cell count\r\n\t\t\thtn\t\t-\thypertension\r\n\t\t\tdm\t\t-\tdiabetes mellitus\r\n\t\t\tcad\t\t-\tcoronary artery disease\r\n\t\t\tappet\t\t-\tappetite\r\n\t\t\tpe\t\t-\tpedal edema\r\n\t\t\tane\t\t-\tanemia\r\n\t\t\tclass\t\t-\tclass\t'

In [32]:
import pandas as pd
chronic_kidney_disease # Get only the dataframe which exist inside the features value
df = chronic_kidney_disease['data']['features']

# Display the first five rows
df.head()

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,hemo,pcv,wbcc,rbcc,htn,dm,cad,appet,pe,ane
0,48.0,80.0,1.020,1.0,0.0,NaN,normal,notpresent,notpresent,121.0,...,15.4,44.0,7800.0,5.2,yes,yes,no,good,no,no
1,7.0,50.0,1.020,4.0,0.0,NaN,normal,notpresent,notpresent,NaN,...,11.3,38.0,6000.0,NaN,no,no,no,good,no,no
2,62.0,80.0,1.010,2.0,3.0,normal,normal,notpresent,notpresent,423.0,...,9.6,31.0,7500.0,NaN,no,yes,no,poor,no,yes
3,48.0,70.0,1.005,4.0,0.0,normal,abnormal,present,notpresent,117.0,...,11.2,32.0,6700.0,3.9,yes,no,no,poor,yes,yes
4,51.0,80.0,1.010,2.0,0.0,normal,normal,notpresent,notpresent,106.0,...,11.6,35.0,7300.0,4.6,no,no,no,good,no,no

In [33]:
print(df.columns)

Index(['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr', 'bu',
       'sc', 'sod', 'pot', 'hemo', 'pcv', 'wbcc', 'rbcc', 'htn', 'dm', 'cad',
       'appet', 'pe', 'ane'],
      dtype='object')

In [34]:
# Copy the dataset 
df = df.copy()

# We need to rename the columns since we cannot understand what each column means
df.rename(columns={'bp': 'blood_press', 'sg': 'specific_gravity',
                   'al':'albumin','su':'sugar',
                   'rbc':'red_blood_cells','pc':'pus_cell',
                   'pcc':'pus_cell_clumps','ba':'bacteria',
                   'bgr':'blood_glucose_random','bu':'blood_urea','sc':'serum creatinine',
                   'sod':'sodium','pot':'potassium','hemo':'hemoglobin',
                   'pcv':'packed_cell_volume','wc':'white_blood_cell_cnt','rc':'red_blood_cell_cnt',
                   'htn':'hypertension','dm':'diabetes_mellitus','cad':'coronary_artery_disease',
                   'appet':'appetite','pe':'pedal_edema','ane':'anemia',
                   'class':'class'}, inplace=True)

In [35]:
df

,age,blood_press,specific_gravity,albumin,sugar,red_blood_cells,pus_cell,pus_cell_clumps,bacteria,blood_glucose_random,...,hemoglobin,packed_cell_volume,wbcc,rbcc,hypertension,diabetes_mellitus,coronary_artery_disease,appetite,pedal_edema,anemia
0,48.0,80.0,1.020,1.0,0.0,NaN,normal,notpresent,notpresent,121.0,...,15.4,44.0,7800.0,5.2,yes,yes,no,good,no,no
1,7.0,50.0,1.020,4.0,0.0,NaN,normal,notpresent,notpresent,NaN,...,11.3,38.0,6000.0,NaN,no,no,no,good,no,no
2,62.0,80.0,1.010,2.0,3.0,normal,normal,notpresent,notpresent,423.0,...,9.6,31.0,7500.0,NaN,no,yes,no,poor,no,yes
3,48.0,70.0,1.005,4.0,0.0,normal,abnormal,present,notpresent,117.0,...,11.2,32.0,6700.0,3.9,yes,no,no,poor,yes,yes
4,51.0,80.0,1.010,2.0,0.0,normal,normal,notpresent,notpresent,106.0,...,11.6,35.0,7300.0,4.6,no,no,no,good,no,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,55.0,80.0,1.020,0.0,0.0,normal,normal,notpresent,notpresent,140.0,...,15.7,47.0,6700.0,4.9,no,no,no,good,no,no
396,42.0,70.0,1.025,0.0,0.0,normal,normal,notpresent,notpresent,75.0,...,16.5,54.0,7800.0,6.2,no,no,no,good,no,no
397,12.0,80.0,1.020,0.0,0.0,normal,normal,notpresent,notpresent,100.0,...,15.8,49.0,6600.0,5.4,no,no,no,good,no,no
398,17.0,60.0,1.025,0.0,0.0,normal,normal,notpresent,notpresent,114.0,...,14.2,51.0,7200.0,5.9,no,no,no,good,no,no
399,58.0,80.0,1.025,0.0,0.0,normal,normal,notpresent,notpresent,131.0,...,15.8,53.0,6800.0,6.1,no,no,no,good,no,no

In [25]:
# Display the rows with null values
df1 = df[df.isna().any(axis=1)]
df1

,age,blood_press,specific_gravity,albumin,sugar,red_blood_cells,pus_cell,pus_cell_clumps,bacteria,blood_glucose_random,...,hemoglobin,packed_cell_volume,wbcc,rbcc,hypertension,diabetes_mellitus,coronary_artery_disease,appetite,pedal_edema,anemia
0,48.0,80.0,1.020,1.0,0.0,NaN,normal,notpresent,notpresent,121.0,...,15.4,44.0,7800.0,5.2,yes,yes,no,good,no,no
1,7.0,50.0,1.020,4.0,0.0,NaN,normal,notpresent,notpresent,NaN,...,11.3,38.0,6000.0,NaN,no,no,no,good,no,no
2,62.0,80.0,1.010,2.0,3.0,normal,normal,notpresent,notpresent,423.0,...,9.6,31.0,7500.0,NaN,no,yes,no,poor,no,yes
4,51.0,80.0,1.010,2.0,0.0,normal,normal,notpresent,notpresent,106.0,...,11.6,35.0,7300.0,4.6,no,no,no,good,no,no
5,60.0,90.0,1.015,3.0,0.0,NaN,NaN,notpresent,notpresent,74.0,...,12.2,39.0,7800.0,4.4,yes,yes,no,good,yes,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
350,65.0,70.0,1.025,0.0,0.0,NaN,NaN,notpresent,notpresent,85.0,...,16.1,43.0,9600.0,4.5,no,no,no,good,no,no
363,67.0,80.0,1.025,0.0,0.0,normal,normal,notpresent,notpresent,99.0,...,17.8,44.0,5900.0,5.2,no,no,no,good,no,no
365,24.0,80.0,1.020,0.0,0.0,normal,normal,notpresent,notpresent,93.0,...,NaN,NaN,10700.0,6.3,no,no,no,good,no,no
378,71.0,60.0,1.025,0.0,0.0,normal,normal,notpresent,notpresent,NaN,...,15.2,42.0,7700.0,5.5,no,no,no,good,no,no
381,71.0,70.0,1.025,0.0,0.0,NaN,NaN,notpresent,notpresent,79.0,...,16.6,40.0,5800.0,5.9,no,no,no,good,no,no